# Generated by Django 4.2.20 on 2025-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
